#!/bin/bash

# Copyright (C) 2021, Bayerische Motoren Werke Aktiengesellschaft (BMW AG),
#   Author: Alexander Domin (Alexander.Domin@bmw.de)
# Copyright (C) 2021, ProFUSION Sistemas e Soluções LTDA,
#   Author: Gustavo Barbieri (barbieri@profusion.mobi)
#   Author: Garbiel Fernandes (g7fernandes@profusion.mobi)
#   Author: Leandro Ferlin (leandroferlin@profusion.mobi)
#   Author: Leonardo Ramos (leo.ramos@profusion.mobi)
#
# SPDX-License-Identifier: MPL-2.0
#
# This Source Code Form is subject to the terms of the
# Mozilla Public License, v. 2.0. If a copy of the MPL was
# not distributed with this file, You can obtain one at
# http://mozilla.org/MPL/2.0/.

set -e

# Check if running inside pipenv
if [ -z "$PIPENV_ACTIVE" ]; then
    exec pipenv run "$0" "$@"
fi
python -V

BASE_PATH="$(git rev-parse --show-toplevel)"
STAGED_CONFIG_FILES="$(git diff --cached --diff-filter=ACMR --oneline --name-only --relative -- 'setup.*')"

# checks if array contains a given element `array_contains [array] [element]`
array_contains () {
  local array="$1[@]"
  local seeking=$2
  local in=1
  for element in "${!array}"; do
      if [[ $element == "$seeking" ]]; then
          in=0
          break
      fi
  done
  return $in
}

if [ -n "$STAGED_CONFIG_FILES" ]; then
  echo "Changed config files, run tests/lint on all files"
  while read -r line; do
    STAGED_PY_FILES_ARRAY+=("$line")
  done <<< "$(git ls-files | grep -E '^.*\.py$')"
else
  while read -r line; do
    STAGED_PY_FILES_ARRAY+=("$line")
  done <<< "$(git diff --cached --diff-filter=ACMR --oneline --name-only -- '*.py')"
fi

FLAKE8=$(which flake8)
MYPY=$(which mypy)

function check_unstaged_modifications {
  local WARN_FLAG
  WARN_FLAG=0
  for F in $(git diff --diff-filter=ACMR --oneline --name-only -- '*.py'); do
    if array_contains STAGED_PY_FILES_ARRAY "$F"; then
      printf "\033[0;31m Warning!\033[0m \033[1m Modified file not commited:\033[0m %s\n" "$F"
      WARN_FLAG=1
      sleep 2
    fi
  done
  if [[ $WARN_FLAG == 1 ]]; then
    printf "\033[0m \033[1mMake sure that you are not forgeting to stage the files above!\033[0m\n"
    echo "Commit process will continue in 5s. Do a Ctrl + C to abort..."
    sleep 5
  fi
}

function test_dependencies {
    if ! type "$FLAKE8" &> /dev/null; then
      printf "\033[41mPlease install Flake8 or make sure that it's in the PATH\033[0m\n"
      return 1
    fi
    if ! type "$MYPY" &> /dev/null; then
      printf "\033[41mPlease install mypy or make sure that it's in the PATH\033[0m\n"
      return 1
    fi

    return 0
}

# Lint check
function call_flake8 {
    if [[ ${STAGED_PY_FILES_ARRAY[0]} == '' ]]; then
        echo "No python files changed, nothing to lint with flake8"
        return 0
    fi

    echo "Linting Python files with Flake8 ($FLAKE8)"

    $FLAKE8 --config "$BASE_PATH/setup.cfg" "${STAGED_PY_FILES_ARRAY[@]}"
    FLAKE8_EXIT=$?

    if [[ "${FLAKE8_EXIT}" == 0 ]]; then
      printf "\033[42mFLAKE8 SUCCEEDED\033[0m\n"
    else
      printf "\033[41mFLAKE8 FAILED:\033[0m Fix flake8 errors and try again\n"
      return 1
    fi

    return 0
}


function run_nose {
  if [[ ${STAGED_PY_FILES_ARRAY[0]} == '' ]]; then
    echo "Nosetests Python files"
    if ! pipenv run python -m nose --with-doctest "${STAGED_PY_FILES_ARRAY[@]}"; then
      printf "\033[41mNOSETESTS FAILED\033[0m\n"
      exit 1
    fi
  fi

  return 0
}

# Typing check
function call_mypy {
  MYPY_ERRORS=false
  if [[ ${STAGED_PY_FILES_ARRAY[0]} == '' ]]; then
      echo "No python files changed, nothing to lint with mypy"
      return 0
  fi

  echo "Type checking Python files with mypy ($MYPY)"

  IGNORE=$(awk -F "= " '/mypy_ignore_folder/ {print $2}' "$BASE_PATH"/setup.cfg)
  IGNORE=$(echo "^""$IGNORE" | sed -r "s/[,]+/|^/g")
  for PYFILE in "${STAGED_PY_FILES_ARRAY[@]}"; do
    if ! grep -Eowq "$IGNORE" <<< "${PYFILE//.\/}"; then
      MYPY_EXIT=$($MYPY --config-file "$BASE_PATH"/setup.cfg $PYFILE)

      if [[ $MYPY_EXIT != *"error"* ]]; then
        printf "\033[42mMYPY SUCCEEDED\033[0m for %s\n" "$PYFILE"
      else
        $MYPY --config-file "$BASE_PATH"/setup.cfg "$PYFILE"
        printf "\033[41mMYPY FOUND PROBLEMS\033[0m for %s$\n" "$PYFILE"
        MYPY_ERRORS=true
      fi

    else
      printf "%s \033[1mignored\033[0m\n" "$PYFILE"
    fi

  done

  if $MYPY_ERRORS; then
    printf "\e[31m\e[1mFix typing errors!\e[0m\n"
    return 1
  fi
  return 0
}

cd "$BASE_PATH"

test_dependencies &&
call_mypy &&
call_flake8 &&
run_nose &&
check_unstaged_modifications
